platform :ios, '9.0'

target 'Example' do

  use_frameworks!
  pod 'ColorMatchTabs', :path => "../"
  
   pod 'YouTubePlayer-Swift','~> 1.0'
   
   pod 'SwiftPhotoGallery'
   
   pod 'FoldingCell', '~> 2.0.3'
   
   pod 'PreviewTransition'
   
   pod 'SKPhotoBrowser'
   pod 'SDWebImage', '~>3.8'
   
   pod 'Firebase/Database'
   pod 'Firebase/Auth'
   pod 'Firebase/Storage'
   pod 'Firebase/Core'
   
   pod 'GVRSDK','~> 0.8.0'
   pod 'YNSearch'
   pod 'ElongationPreview'
   pod 'Twinkle'
end
